### PR TITLE
82 Texture Addition

### PR DESCRIPTION
**Pull request by TekhnaeRaav**
I've added a bunch of textures that I hope you'll like. This nearly finishes it off, there is only a few missing textures still.

Kept everything as consistent as I could with all the colors and patterns. Changes the progress bar, hearts and bubbles. Adds all the rest of the trees, adds all ingots. I finished silver sand/sandstone, desert sand/sandstone. All cart textures are added. And I renamed your ladder texture(It was the wrong name) and I added the steel ladder. Oh, and I did the rainforest litter.

### CODE REVIEW

**Comment by TekhnaeRaav** [comment]
All right that, thats it. Ready to merge! Hope you like it!

**Comment by TekhnaeRaav** [comment]
Added a few more things... I don't know how much your on here, so if you don't mind me pinging you @davisonio 
Oh, I also changed the color of the default leaves to be darker than the birch should be.

**Comment by davisonio** [comment]
@TekhnaeRaav thanks so much! These are great - really appreciate it. Have just merged this into latest version. :)

**Comment by TekhnaeRaav** [comment]
Your welcome! I liked the texture pack, so I thought I'd put a bit more of it together.
Glad you like them. ^_^

**Pull request merged**
